
# Note: while it is possible to create PR without special token, the special token
# is needed for the PR to trigger further Github Actions. To do that use an App:
# https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs

# This script is automatically updated from: https://github.com/mverleg/ci_util/tree/master/github_action

name: 'Bump dependencies'

on:
  schedule:
    - cron: '0 9 1,16 * *'
  workflow_dispatch:

jobs:
  checks:
    name: Bump dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get date
        id: date
        run: |
          echo "::set-output name=DATE_CODE::$(date +'%Y-%m-%d')"
          echo "::set-output name=DATE_NAME::$(date +'%B %Y')"
      - name: Self-update bumper action
        run: |
          curl --silent https://raw.githubusercontent.com/mverleg/ci_util/master/github_action/bump-dependencies.yml --output .github/workflows/bump-dependencies.yml
      - name: Docker bump
        if: hashFiles('ci/upgrade_docker_base.sh') != ''
        run: |
          sh ci/upgrade_docker_base.sh
      - name: Cargo bump
        if: hashFiles('Cargo.toml') != ''
        run: |
          printf 'FROM mverleg/pastacode-base:latest\n' > "$TMPDIR/bump-dependencies.Dockerfile"
          printf 'COPY . ./\n' >> "$TMPDIR/bump-dependencies.Dockerfile"
          printf 'RUN cargo upgrade && cargo update\n' >> "$TMPDIR/bump-dependencies.Dockerfile"
          printf 'RUN cargo --offline outdated --exit-code 1\n' >> "$TMPDIR/bump-dependencies.Dockerfile"
          cat "$TMPDIR/bump-dependencies.Dockerfile"
          docker build -t dependencies-image -f "$TMPDIR/bump-dependencies.Dockerfile" .
          id=$(docker create dependencies-image)
          docker cp $id:/volume/Cargo.toml Cargo.toml
          docker cp $id:/volume/Cargo.lock Cargo.lock
      - name: Changes?
        id: is_changed
        run: |
          if ! git diff --exit-code Cargo.* ci/*.Dockerfile
          then
              echo "CHANGED!"
              echo "::set-output name=IS_CHANGED::1"
          else
              echo "not changed"
          fi
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.PR_BOT_APP_ID }}
          private_key: ${{ secrets.PR_BOT_PRIV_KEY }}
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        if: ${{ steps.is_changed.outputs.IS_CHANGED == '1' }}
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "Automatic version bump ${{ steps.date.outputs.DATE_NAME }}"
          title: "Automatic version bump ${{ steps.date.outputs.DATE_NAME }}"
          body: "Created by Github Action to bump Docker and Cargo versions"
          author: "DependencyBumper <mverleg.noreply@gmail.com>"
          committer: "DependencyBumper <mverleg.noreply@gmail.com>"
          branch: "bump-${{ steps.date.outputs.DATE_CODE }}"
          assignees: "mverleg"
          delete-branch: true
